<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Generic.Extensions">
      <HintPath>E:\Dokumentacja studencka\Semestr IV\Programowanie obiektowe\Generic.Extensions\bin\Release\net8.0\Generic.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
