<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lab5.bll\Lab5.bll.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Generic.Extensions">
      <HintPath>..\..\Lab4\Generic.Extensions\bin\Release\net8.0\Generic.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
